[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Packages.php-fpm",
  "php82Extensions.pdo_mysql",
  "nodejs_18",
  "nginx"
]
aptPkgs = ["adduser"]

cmds = [
  "php -v",
  "composer --version"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan cache:clear",
  "mkdir -p storage/framework/{sessions,views,cache} storage/logs bootstrap/cache",
  "chmod -R 775 storage bootstrap/cache",
  "chown -R www-data:www-data storage bootstrap/cache || true",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "npm ci",
  "npm run build",
  "mkdir -p /etc/nginx",
  "cp config/nginx.conf /etc/nginx/nginx.conf",
  "cp config/php-fpm.conf /app/config/php-fpm.conf"
]

[phases.start]
cmd = '''
mkdir -p /run/php && \
chown -R www-data:www-data /run/php && \
mkdir -p storage/framework/{sessions,views,cache} storage/logs bootstrap/cache && \
chown -R www-data:www-data storage bootstrap/cache && \
chmod -R 775 storage bootstrap/cache && \
php artisan migrate --force && \
php-fpm -y /app/config/php-fpm.conf & \
nginx -c /etc/nginx/nginx.conf -g "daemon off;"
'''
