[phases.setup]
nixPkgs = [
    "php82",
    "php82Packages.composer",
    "php82Packages.php-fpm",
    "php82Extensions.pdo_mysql",
    "nodejs_18",
    "nginx"
]
aptPkgs = ["adduser"]

cmds = [
    "echo 'Setup Phase: Installing Composer'",
    "php -v",
    "composer --version",
    "echo 'Setup Phase Complete'"
]

[phases.build]
cmds = [
    "echo 'Build Phase: Running composer install'",
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:clear",
    "php artisan cache:clear",
    # Ensure all necessary storage subdirectories exist
    "mkdir -p storage/framework/{sessions,views,cache} storage/logs bootstrap/cache",
    # Set permissions and ownership for storage and bootstrap/cache
    "chmod -R 775 storage bootstrap/cache",
    "chown -R www-data:www-data storage bootstrap/cache",
    "php artisan migrate --force",
    "npm ci",
    "npm run build",
    # Copy configuration files to appropriate locations
    "mkdir -p /etc/nginx",
    "cp config/nginx.conf /etc/nginx/nginx.conf",
    "cp config/php-fpm.conf /app/config/php-fpm.conf"
]

[phases.start]
cmd = '''
echo "Starting PHP-FPM and Nginx..." &&
# Get PHP-FPM process information
PHP_USER=$(ps aux | grep php-fpm | grep -v grep | awk '{print $1}') &&
PHP_GROUP=$(ps aux | grep php-fpm | grep -v grep | awk '{print $2}') &&
echo "PHP-FPM User: $PHP_USER" &&
echo "PHP-FPM Group: $PHP_GROUP" &&
# Correctly set ownership and permissions
chown -R $PHP_USER:$PHP_GROUP storage bootstrap/cache &&
chmod -R 775 storage bootstrap/cache &&
php-fpm -y /app/config/php-fpm.conf &
nginx -c /etc/nginx/nginx.conf -g "daemon off;"
'''
