[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Packages.php-fpm",
  "php82Extensions.pdo_mysql",
  "nodejs_18",
  "nginx"
]
aptPkgs = ["adduser"]

[phases.build]
cmds = [
  "adduser --system --group www-data || true",
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan cache:clear",
  "mkdir -p storage/framework/sessions",
  "chmod -R 775 storage",
  "chown -R www-data:www-data storage",
  "php artisan migrate --force",
  "npm ci",
  "npm run build",
  "mkdir -p /etc/nginx/ssl",
  "cp config/nginx.conf /etc/nginx/nginx.conf",
  "cp config/php-fpm.conf /etc/php-fpm.conf",
  "cp config/server.crt /etc/nginx/ssl/server.crt",
  "cp config/server.key /etc/nginx/ssl/server.key"
]

[phases.start]
cmd = "php-fpm -y /etc/php-fpm.conf & nginx -c /etc/nginx/nginx.conf -g 'daemon off;'"
