[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Packages.php-fpm",
  "php82Extensions.pdo_mysql",
  "nodejs_18",
  "nginx"
]
aptPkgs = ["adduser"]

cmds = [
  "echo 'Setup Phase: Installing Composer'"
]

[phases.build]
cmds = [
  "echo 'Build Phase: Running composer install'",
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan cache:clear",
  "mkdir -p storage/framework/sessions",
  "chmod -R 775 storage",
  "chown -R www-data:www-data storage",
  "php artisan migrate --force",
  "npm ci",
  "npm run build",
  "mkdir -p /etc/nginx",
  "cp config/nginx.conf /etc/nginx/nginx.conf",
  "cp config/php-fpm.conf /app/config/php-fpm.conf"
]

[phases.start]
cmd = '''
php artisan migrate --force && \
php-fpm -y /app/config/php-fpm.conf & \
nginx -c /app/config/nginx.conf -g "daemon off;"
'''
