# .nixpacks.toml

[phases.setup]
# Ensures PHP, Composer, Node.js, and Corepack are installed
nixPkgs = ['php', 'phpPackages.composer', 'nodejs', 'corepack']

[phases.build]
# Commands to install PHP and Node.js dependencies, and build frontend assets
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'corepack enable',
  'npm install',
  'npm run build'
]

[start]
# Starts the Laravel application using the built-in PHP dev server
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
